# Site settings
name: Matt Goldman
title: mattgoldman.us
email: matt@mattgoldman.us
description: "Rutgers CS/Math major and general tech enthusiast"
baseurl: ""
url: "http://mattgoldman.us"

# Build settings
highlighter: pygments
permalink: /blog/:year/:title/
exclude: [s3_website.yml]



pages_list:
  - Home: '/'
  - Projects: '/projects'
  - Résumé: '/cv'
  - Blog: '/blog'
  - FAQ: '/faq'
  - Contact: '/contact'
