# Site settings
name: Matt Goldman
title: mattgoldman.us
email: matt@mattgoldman.us
description: "Rutgers CS/Math major and general tech enthusiast"
baseurl: ""
url: "http://mattgoldman.us"

# Build settings
highlighter: pygments
permalinks: pretty
exclude: [s3_website.yml]



pages_list:
  Home: '/'
  Contact: '/contact'
  FAQ: '/faq'
  Résumé: '/cv'
  Projects: '/projects'
