# Site settings
name: Matt Goldman
title: mattgoldman.us
email: matt@mattgoldman.us
description: "NJ Geek"
baseurl: ""
url: "http://mattgoldman.us"

# Build settings
highlighter: pygments
permalink: /blog/:year/:title/
exclude: [s3_website.yml, vendor, Gemfile, Gemfile.lock, Rakefile, README.md, build.sh]

excerpt-separator: ""

pages_list:
  - Projects: '/projects'
  - Résumé: '/cv'
  - 2CV: '/2cv'
  - Blog: '/blog'
  - FAQ: '/faq'
  - Contact: '/contact'
